### ISSUE TITLE
Not working with iTerm2 Nightly (Build 2.9.20150301-nightly)

### ISSUE THREAD

**Issue by sideshowbarker** [quicksilver/iTerm2-qsplugin#5]
I have iTerm2 Nightly (Build 2.9.20150301-nightly) installed and I have iTerm2 set for the `Command Line Interface` option in Quicksilver, but when I select commands from my bash history in Quicksilver, nothing happens (the commands don't get run in iTerm2 nor anywhere else).

**Comment by gnachman** [comment]
iTerm's Applescript changed in 2.9, breaking backward compatibility. The old syntax didn't support split panes and used outdated terminology. The new syntax is described here: iterm2.com/applescript.html

**Comment by skurfer** [comment]
Follow quicksilver/Quicksilver#2086 for updates on this
